# Generated by Django 5.1.3 on 2024-11-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_author_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='T', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='T', max_length=40),
        ),
    ]
